using FreeSql.DatabaseModel;
using RazorEngine;
using RazorEngine.Configuration;
using RazorEngine.Templating;
using RazorEngine.Text;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace Context
{
    public class CodeGenerate
    {
        public async Task<List<string>> Setup(TaskBuild taskBuild, string tableName)
        {
            DbTableInfo tableInfo = taskBuild.tableInfos.Where(a=>a.Name== tableName).FirstOrDefault();
            try
            {
                var listText =  await Task.Run(() =>
                {
                    var config = new TemplateServiceConfiguration();
                    config.EncodedStringFactory = new RawStringFactory();
                    Engine.Razor = RazorEngineService.Create(config);

                    List<string> listCodeResult = new List<string>();

                    foreach (var template in taskBuild.Templates)
                    {
                        var razorId = Guid.NewGuid().ToString("N");
                        if (string.IsNullOrWhiteSpace(template.TemplateText))
                        {
                            var html = File.ReadAllText(Path.Combine(Environment.CurrentDirectory, "", template.TemplatePath));
                            Engine.Razor.Compile(html, razorId);
                        }
                        else
                        {
                            Engine.Razor.Compile(template.TemplateText, razorId);
                        }
                        //开始生成操作
                        var sw = new StringWriter();
                        var model = new EntityTemplate(taskBuild, tableInfo);
                        Engine.Razor.Run(razorId, sw, null, model);
                        StringBuilder plus = new StringBuilder();
                        plus.AppendLine("//------------------------------------------------------------------------------");
                        plus.AppendLine("// <auto-generated>");
                        plus.AppendLine("//     此代码由工具生成。");
                        plus.AppendLine("//     对此文件的更改可能会导致不正确的行为，并且如果");
                        plus.AppendLine("//     重新生成代码，这些更改将会丢失。");
                        plus.AppendLine("// </auto-generated>");
                        plus.AppendLine("//------------------------------------------------------------------------------");
                        plus.Append(sw.ToString());
                        plus.AppendLine();
                        listCodeResult.Add(plus.ToString());
                    }

                    return listCodeResult;
                });
                return listText;
            }
            catch (Exception ex)
            {
                Common.Console.Log("=========Setup==========");
                Common.Console.Log(ex.ToString());
                return new List<string>();
            }
        }
        /// <summary>
        /// 传入任务信息
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<string> Setup(TaskBuild taskBuild, List<DbTableInfo> outputTables)
        {
            try
            {
                var paths = await Task.Run(() =>
                {
                    var config = new TemplateServiceConfiguration();
                    config.EncodedStringFactory = new RawStringFactory();
                    Engine.Razor = RazorEngineService.Create(config);

                    string path = string.Empty;


                    foreach (var template in taskBuild.Templates)
                    {
                        path = $"{taskBuild.GeneratePath}\\{taskBuild.DbName}\\{template.TemplatePath.Replace(".cshtml", "").Trim()}";
                        if (!Directory.Exists(path)) Directory.CreateDirectory(path);

                        var razorId = Guid.NewGuid().ToString("N");
                        if (string.IsNullOrWhiteSpace(template.TemplateText))
                        {
                            var html = File.ReadAllText(Path.Combine(Environment.CurrentDirectory, "Templates", template.TemplatePath));
                            Engine.Razor.Compile(html, razorId);
                        }
                        else
                        {
                            Engine.Razor.Compile(template.TemplateText, razorId);
                        }
                        //开始生成操作
                        foreach (var table in outputTables)
                        {
                            var sw = new StringWriter();
                            var model = new EntityTemplate(taskBuild, table);
                            Engine.Razor.Run(razorId, sw, null, model);
                            StringBuilder plus = new StringBuilder();
                            plus.AppendLine("//------------------------------------------------------------------------------");
                            plus.AppendLine("// <auto-generated>");
                            plus.AppendLine("//     此代码由工具生成。");
                            plus.AppendLine("//     对此文件的更改可能会导致不正确的行为，并且如果");
                            plus.AppendLine("//     重新生成代码，这些更改将会丢失。");
                            plus.AppendLine("// </auto-generated>");
                            plus.AppendLine("//------------------------------------------------------------------------------");
                            plus.Append(sw.ToString());
                            plus.AppendLine();
                            var outPath = $"{path}\\{taskBuild.FileName.Replace("{name}", model.GetCsName(table.Name))}";
                            if (!string.IsNullOrEmpty(taskBuild.FilterTableChar))
                                outPath = outPath.Replace(taskBuild.FilterTableChar, "").Trim();
                            File.WriteAllText(outPath, plus.ToString());
                        }
                    }
                    return path;
                });
                Process.Start(paths);
                return "生成成功";
            }
            catch (Exception ex)
            {
                return $"生成时发生异常,请检查模版代码: {ex.Message}.";
            }
        }

        public async Task<string> Setup(TaskBuild taskBuild, string code, List<DbTableInfo> dbTables, DbTableInfo dbTableInfo)
        {
            StringBuilder plus = new StringBuilder();
            try
            {
                var config = new TemplateServiceConfiguration();
                config.EncodedStringFactory = new RawStringFactory();
                Engine.Razor = RazorEngineService.Create(config);
                var razorId = Guid.NewGuid().ToString("N");
                Engine.Razor.Compile(code, razorId);

                var sw = new StringWriter();
                var model = new EntityTemplate(taskBuild, dbTableInfo);
                Engine.Razor.Run(razorId, sw, null, model);

                plus.AppendLine("//------------------------------------------------------------------------------");
                plus.AppendLine("// <auto-generated>");
                plus.AppendLine("//     此代码由工具生成。");
                plus.AppendLine("//     对此文件的更改可能会导致不正确的行为，并且如果");
                plus.AppendLine("//     重新生成代码，这些更改将会丢失。");
                plus.AppendLine("// </auto-generated>");
                plus.AppendLine("//------------------------------------------------------------------------------");
                plus.Append(sw.ToString());
                plus.AppendLine();
                return await Task.FromResult(plus.ToString());
            }
            catch
            {
                return await Task.FromResult(plus.ToString());
            }
        }
    }
}
